### ISSUE TITLE
Quarkus migrations

### ISSUE THREAD

**Issue by okundzich** [openrewrite/rewrite-quarkus#1]
Create a new repository for this.

Migration guides
https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.0

2.0 release is coming out soon (June).

Demo repository is still on 1.11.
https://github.com/cescoffier/reactive-coffeeshop-demo/blob/master/pom.xml

**Comment by pway99** [comment]
Closing this issue in favor of the several issues created for this conversion.
