### ISSUE TITLE
2.0: Quarkus @ConfigProperties annotated class to SmallRye Config @ConfigMapping annotated interface

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite-quarkus#24]
SmallRye [ConfigMappings](https://smallrye.io/docs/smallrye-config/main/mapping/mapping.html)

> A Config Mapping requires an interface with minimal metadata configuration:

```java
@ConfigMapping(prefix = "server")
interface Server {
    String host();

    int port();
}
```

Quarkus `@ConfigProperties` are allowed on classes while `@ConfigMapping` is only valid for interfaces
https://quarkus.io/guides/config-reference#using_configproperties
https://quarkus.io/guides/config-reference#additional-notes-on-configproperties

This task is to refactor `@ConfigProperties` configuration `classes` and associated variable references annotated with to interfaces and methodInvocations

before:
```java
import io.quarkus.arc.config.ConfigProperties;

@ConfigProperties(prefix = "greeting")
public class MyConfiguration {
    String message;
    String name;
}
public class MyService {
  @Inject
  MyConfiguration myConfig;
  
  String getName() {
    return myConfig.name;
  }
}
```
after:
```java
import io.smallrye.config.ConfigMapping;

@ConfigMapping(prefix = "greeting")
public interface MyConfiguration {
    String message();
    String name();
}
public class MyService {
  @Inject
  MyConfiguration myConfig;
  
  String getName() {
    return myConfig.name();
  }
}
```

**Comment by tkvangorder** [comment]
Closing because this has been open for almost a year.
